version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URI=${DATABASE_URI}
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=${API_URL}
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
